# Generated by Django 5.0.2 on 2025-05-22 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PSIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_time', models.DateTimeField(blank=True, null=True)),
                ('strategy', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=16, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psi_reports', to='links.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fetch_time'],
            },
        ),
        migrations.CreateModel(
            name='LabMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcp_s', models.FloatField(null=True)),
                ('lcp_s', models.FloatField(null=True)),
                ('speed_index_s', models.FloatField(null=True)),
                ('tti_s', models.FloatField(null=True)),
                ('tbt_ms', models.FloatField(null=True)),
                ('cls', models.FloatField(null=True)),
                ('performance_score', models.FloatField(null=True)),
                ('psi_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_metrics', to='links.psireport')),
            ],
        ),
        migrations.CreateModel(
            name='FieldMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcp_ms', models.FloatField(null=True)),
                ('lcp_ms', models.FloatField(null=True)),
                ('fid_ms', models.FloatField(null=True)),
                ('inp_ms', models.FloatField(null=True)),
                ('cls', models.FloatField(null=True)),
                ('ttfb_ms', models.FloatField(null=True)),
                ('overall_category', models.CharField(max_length=32, null=True)),
                ('has_data', models.BooleanField(default=False)),
                ('psi_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_metrics', to='links.psireport')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.FloatField(null=True)),
                ('accessibility', models.FloatField(null=True)),
                ('best_practices', models.FloatField(null=True)),
                ('seo', models.FloatField(null=True)),
                ('psi_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='links.psireport')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('audit_key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('score', models.FloatField(null=True)),
                ('score_display_mode', models.CharField(max_length=32, null=True)),
                ('display_value', models.CharField(max_length=256, null=True)),
                ('details', models.JSONField(null=True)),
                ('psi_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='links.psireport')),
            ],
        ),
        migrations.CreateModel(
            name='PSIReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_time', models.DateTimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_report_groups', to='links.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_report_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='psireport',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='links.psireportgroup'),
        ),
    ]
