# Generated by Django 5.0.2 on 2025-05-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile_report', models.JSONField()),
                ('desktop_report', models.JSONField()),
                ('mobile_performance_score', models.FloatField()),
                ('desktop_performance_score', models.FloatField()),
                ('mobile_lcp', models.FloatField(null=True)),
                ('mobile_fid', models.FloatField(null=True)),
                ('mobile_cls', models.FloatField(null=True)),
                ('desktop_lcp', models.FloatField(null=True)),
                ('desktop_fid', models.FloatField(null=True)),
                ('desktop_cls', models.FloatField(null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_reports', to='links.link')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
