# Generated by Django 5.0.2 on 2025-05-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_psireport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psireport',
            name='desktop_cls',
        ),
        migrations.RemoveField(
            model_name='psireport',
            name='desktop_fid',
        ),
        migrations.RemoveField(
            model_name='psireport',
            name='desktop_lcp',
        ),
        migrations.RemoveField(
            model_name='psireport',
            name='desktop_performance_score',
        ),
        migrations.RemoveField(
            model_name='psireport',
            name='mobile_cls',
        ),
        migrations.RemoveField(
            model_name='psireport',
            name='mobile_fid',
        ),
        migrations.RemoveField(
            model_name='psireport',
            name='mobile_lcp',
        ),
        migrations.RemoveField(
            model_name='psireport',
            name='mobile_performance_score',
        ),
    ]
