# Generated by Django 4.2.21 on 2025-05-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0003_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SSLLabsScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('subject', models.TextField(blank=True)),
                ('issuer', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('not_before', models.DateTimeField(null=True)),
                ('not_after', models.DateTimeField(null=True)),
                ('san', models.TextField(blank=True)),
                ('signature_algorithm', models.CharField(blank=True, max_length=128)),
                ('public_key_type', models.CharField(blank=True, max_length=64)),
                ('public_key_bits', models.IntegerField(null=True)),
                ('ocsp_url', models.TextField(blank=True)),
                ('crl_url', models.TextField(blank=True)),
                ('chain_issues', models.TextField(blank=True)),
                ('hsts', models.BooleanField(default=False)),
                ('hsts_max_age', models.IntegerField(null=True)),
                ('hsts_preload', models.BooleanField(default=False)),
                ('forward_secrecy', models.BooleanField(default=False)),
                ('protocols', models.TextField(blank=True)),
                ('ciphers', models.TextField(blank=True)),
                ('vulnerabilities', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('errors', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssllabs_scans', to='links.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssllabs_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='SSLCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.TextField()),
                ('issuer', models.TextField()),
                ('serial_number', models.CharField(max_length=128)),
                ('version', models.IntegerField(null=True)),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('san', models.TextField(blank=True)),
                ('signature_algorithm', models.CharField(blank=True, max_length=128)),
                ('public_key_type', models.CharField(blank=True, max_length=64)),
                ('public_key_bits', models.IntegerField(null=True)),
                ('ocsp_url', models.TextField(blank=True)),
                ('crl_url', models.TextField(blank=True)),
                ('chain_count', models.IntegerField(default=1)),
                ('is_self_signed', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_weak_signature', models.BooleanField(default=False)),
                ('is_short_key', models.BooleanField(default=False)),
                ('warnings', models.TextField(blank=True)),
                ('errors', models.TextField(blank=True)),
                ('raw_cert', models.TextField(blank=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_checks', to='links.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
