# Generated by Django 5.0.2 on 2025-05-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_page_remove_psireport_desktop_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psireport',
            options={'ordering': ['-fetch_time']},
        ),
        migrations.RemoveField(
            model_name='psireport',
            name='created_at',
        ),
    ]
