# Generated by Django 5.0.2 on 2025-05-20 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_psireport_options_remove_psireport_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSIReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_time', models.DateTimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psi_report_groups', to='links.page')),
            ],
        ),
        migrations.AddField(
            model_name='psireport',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='links.psireportgroup'),
        ),
    ]
