# Generated by Django 5.0.2 on 2025-05-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_group_existing_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmetrics',
            name='overall_category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
