name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DJANGO_SECRET_KEY: testsecretkey
      PSI_API_KEY: testapikey
      DJANGO_DEBUG: 'False'
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: postgres://user:pass@localhost:5432/test_db
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: |
          python manage.py migrate
      - name: List installed packages
        run: pip list
      - name: Run tests
        run: |
          pytest --ds=webassist.settings --cov=webassist
      - name: Check formatting
        run: |
          black --check .
          isort --check-only .
      - name: Clear mypy cache
        run: rm -rf .mypy_cache
      - name: Type check
        run: |
          mypy webassist --install-types --non-interactive -v 